version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: GoogleCloudPlatform:master    # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_stat
  - base: develop
    upstream: GoogleCloudPlatform:develop
    mergeMethod: hardreset
    mergeUnstable: false
