# Copyright 2024 "Google LLC"
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "1"
rules:                      # Array of rules
- base: main            # Required. Target branch
  upstream: GoogleCloudPlatform:main    # Required. Must be in the same fork network.
  mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
  mergeUnstable: false    # Optional, merge pull request even when the mergeable_stat
- base: develop
  upstream: GoogleCloudPlatform:develop
  mergeMethod: hardreset
  mergeUnstable: false
- base: experimental
  upstream: GoogleCloudPlatform:experimental
  mergeMethod: hardreset
  mergeUnstable: false
